return {
  ["893973440"] = "https://raw.githubusercontent.com/Zynkore/Hub/refs/heads/main/Games/Flee%20the%20facility/Select.lua", -- Flee the facility
  ["2753915549"] = "https://raw.githubusercontent.com/MarkhubOfc/Mark-Hub/refs/heads/main/Games/BloxFruits/Sea1.lua", -- Blox fruits ( sea 1 )
  ["6250795236"] = "https://raw.githubusercontent.com/Zynkore/Hub/refs/heads/main/Games/SNK%3ARumbling/Select.lua", -- SNK:Rumbling ( Rumbling map )
}
